name: date_utils
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Eric Windmill <ericwindmill@gmail.com>
description: A Dart library for manipulating DateTimes.
version: 0.0.1
#homepage: https://www.example.com

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  intl: ^0.15.0

dev_dependencies:
  test: ^0.12.0
